apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev
  name: sample-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - image: mekala/python-demo-app:demo-app-1.0
        name: python-demo-app
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: sample-docker-secret    
