apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    env: demo
spec:
  type: NodePort
  ports:
    - nodePort: 30007 
      port: 80
      targetPort: 80
  selector:
    env: demo  
