apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - image: mekala/multistage:latest
        name: multistage
        envFrom:
        - configMapRef:
            name: sample-cm
        ports:
        - containerPort: 8080
