apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev
  name: svc-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: dev
  type: NodePort   
