apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels: 
    name: myapp-pod
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.35
    command: ["sh", "-c", "until nslookup myservice.default.svc.cluster.local; do echo waiting for service to be up; sleep 2; done"]
  - name: init-mydb
    image: busybox:1.35
    command: ["sh", "-c", "until nslookup mydb.default.svc.cluster.local; do echo waiting for service to be up; sleep 2; done"]  
  #App Container  
  containers: 
  - name: myapp-container
    image: busybox:1.35
    command: ["sh", "-c", "echo the app is running && sleep infinity"]
    env:
    - name: FIRSTNAME
      value: "viswa"
