apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels: 
    name: myapp-pod
spec:
  containers: 
  - name: myapp-container
    image: busybox:1.35
    command: ["sh", "-c", "echo the app is running && sleep infinity"]
    env:
    - name: FIRSTNAME
      valueFrom:
        configMapKeyRef:
          name: app-cm
          key: firstname
