apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-app-deploy
  labels:
    name: results-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: results-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: results-app-pod
      labels:
        name: results-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: results-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80