name: Deploy to AWS

on:
  push:
    branches:
      - master  # Replace with your branch
env:
  BUCKET_NAME : "github-action-demo-bucket"
  AWS_REGION : "us-east-1"  
permissions:
  id-token: write
  contents: read      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials from OpenID Connect
        uses: aws-actions/configure-aws-credentials@v3
        with:
          #audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::407303461057:role/Githubactions-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy myfile.txt to s3
        run: |
          # Your deployment commands here, e.g., Copying objects into s3 bucket
          aws s3 cp ./myfile.txt s3://${{ env.BUCKET_NAME }}/
