name: Deploy to AWS

on:
  push:
    branches:
      - main  # Replace with your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials from OpenID Connect
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::407303461057:role/Githubactions-Role
          aws-region: us-east-1

      - name: Deploy to AWS
        run: |
          # Your deployment commands here, e.g., AWS CLI commands
          aws s3 cp aws-fundamentals/myfile.txt s3://github-action-demo-bucket/
